apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "quarkus-template.fullname" . }}-app-properties
  labels:
    {{- include "quarkus-template.labels" . | nindent 4 }}
data:
  application.properties: |
    quarkus.http.port={{ .Values.quarkus.httpPort | default .Values.global.quarkus.httpPort }}
    {{- if or .Values.quarkus.metricsPort .Values.global.quarkus.metricsPort }}
    quarkus.management.enabled=true
    quarkus.management.port={{ .Values.quarkus.metricsPort | default .Values.global.quarkus.metricsPort }}
    {{- end }}
    {{- if .Values.global.truststore }}
    quarkus.tls.trust-all=true
    {{- end }}
    {{- if .Values.applicationProperties }}
    {{ .Values.applicationProperties | nindent 4 }}
    {{- end }}
  application.yaml: |
    {{- $appYaml := dict }}
    {{- if .Values.applicationYaml }}
    {{- $appYaml = merge $appYaml .Values.applicationYaml }}
    {{- end }}
    {{- if .Values.global.applicationYaml }}
    {{- $appYaml = merge $appYaml .Values.global.applicationYaml }}
    {{- end }}
    {{- if and .Values.kafka.enabled .Values.global.kafka.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.kafka.applicationYaml }}
    {{- end }}
    {{- if and .Values.minio.enabled .Values.global.minio.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.minio.applicationYaml }}
    {{- end }}
    {{- if and .Values.clickhouse.enabled .Values.global.clickhouse.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.clickhouse.applicationYaml }}
    {{- end }}
    {{- if and .Values.oidc.enabled .Values.global.oidc.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.oidc.applicationYaml }}
    {{- end }}
    {{- if and .Values.openfga.enabled .Values.global.openfga.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.openfga.applicationYaml }}
    {{- end }}
    {{- if and .Values.keycloakAdmin.enabled .Values.global.keycloakAdmin.applicationYaml}}
    {{- $appYaml = merge $appYaml .Values.global.keycloakAdmin.applicationYaml }}
    {{- end }}
    {{- toYaml $appYaml | nindent 4 }}
